# Do not print newline after prompt
add_newline = false

[username]
show_always = true

[character]
success_symbol = "[➤](bold green) "
error_symbol = "[✗](bold red) "

[kubernetes]
disabled = true

[helm]
disabled = false

[terraform]
disabled = false


