# Do not print newline after prompt
add_newline = false

[username]
show_always = false
format = "[$user]($style) "

[hostname]
disabled = false
ssh_only= true
format = "@ [$hostname]($style) "
style = "blue"

[directory]
truncation_length = 8
truncation_symbol = "…/"

[character]
success_symbol = "[ᑀ](bold green) "
error_symbol = "[⤬](bold red) "

[kubernetes]
disabled = true

[helm]
disabled = false

[terraform]
disabled = true

[git_branch]
format = "[$symbol$branch]($style)"

