".local/share/fonts/firacode":
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
  refreshPeriod: 169h
  exact: false

".local/share/fonts/lekton":
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Lekton.zip
  refreshPeriod: 169h
  exact: false
".local/share/fonts/gocode":
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Go-Mono.zip
  refreshPeriod: 169h
  exact: false

