directory: ~/Music

threaded: yes

paths:
  default: $albumartist/$album%aunique{}/$track - $title
  singelton: $artist/singles/$title
  comp: Compilations/$album%aunique{}/$track - $title
  albumtype_soundtrack: Soundtracks/$album/$track $title
