# ~/.config/yazi/keymap.toml — managed by chezmoi

[[mgr.prepend_keymap]]
on  = "<C-t>"
run = "plugin tv"
desc = "Jump to a file via television"

[[mgr.prepend_keymap]]
on  = "<C-d>"
run = "plugin tv dirs"
desc = "Jump to a directory via television"

[[mgr.prepend_keymap]]
on  = "<C-f>"
run = "plugin tv text"
desc = "Open files using neovim and jump to where the string is located"
