
# kubectl convenience aliases
## base
alias k "kubectl"

## attach
alias katt "kubectl attach"
alias katti "kubectl attach --stdin --tty"

## apply
alias ka "kubectl apply"
alias kaf "kubectl apply -f"
alias kafr "kubectl apply --recursive -f"

## edit
alias ke "kubectl edit"
alias kecm "kubectl edit configmaps"
alias kecrd "kubectl edit customresourcedefitions"
alias keds "kubectl edit daemonsets"
alias ked "kubectl edit deployments"
alias kehpa "kubectl edit horizontalpodautoscalers"
alias kei "kubectl edit ingress"
alias kej "kubectl edit jobs"
alias kens "kubectl edit namespaces"
alias ken "kubectl edit nodes"
alias kepvc "kubectl edit persistentvolumeclaims"
alias kepv "kubectl edit persistentvolumes"
alias kep "kubectl edit pods"
alias kers "kubectl edit replicasets"
alias kerb "kubectl edit rolebindings"
alias ker "kubectl edit roles"
alias kes "kubectl edit secrets"
alias kesa "kubectl edit serviceaccounts"
alias kesvc "kubectl edit services"
alias kess "kubectl edit statefulsets"
alias kesc "kubectl edit storageclasses"
alias keva "kubectl edit volumeattachments"
alias kewli "kubectl edit workloadimages"

## delete
### Example `kdeld kfgp {deployment name}`
alias kdel "kubectl delete"
alias kdelcm "kubectl delete configmaps"
alias kdelcrd "kubectl delete customresourcedefitions"
alias kdelds "kubectl delete daemonsets"
alias kdeld "kubectl delete deployments"
alias kdelhpa "kubectl delete horizontalpodautoscalers"
alias kdeli "kubectl delete ingress"
alias kdelj "kubectl delete jobs"
alias kdelns "kubectl delete namespaces"
alias kdeln "kubectl delete nodes"
alias kdelpvc "kubectl delete persistentvolumeclaims"
alias kdelpv "kubectl delete persistentvolumes"
alias kdelp "kubectl delete pods"
alias kdelrs "kubectl delete replicasets"
alias kdelrb "kubectl delete rolebindings"
alias kdelr "kubectl delete roles"
alias kdels "kubectl delete secrets"
alias kdelsa "kubectl delete serviceaccounts"
alias kdelsvc "kubectl delete services"
alias kdelss "kubectl delete statefulsets"
alias kdelsc "kubectl delete storageclasses"
alias kdelva "kubectl delete volumeattachments"
alias kdelwli "kubectl delete workloadimages"

## describe
alias kd "kubectl describe"
alias kdcm "kubectl describe configmaps"
alias kdcrd "kubectl describe customresourcedefinitions"
alias kdds "kubectl describe daemonsets"
alias kdd "kubectl describe deployments"
alias kdhpa "kubectl describe horizontalpodautoscalers"
alias kdi "kubectl describe ingress"
alias kdj "kubectl describe jobs"
alias kdns "kubectl describe namespaces"
alias kdn "kubectl describe nodes"
alias kdpvc "kubectl describe persistentvolumeclaims"
alias kdpv "kubectl describe persistentvolumes"
alias kdp "kubectl describe pods"
alias kdrs "kubectl describe replicasets"
alias kdrb "kubectl describe rolebindings"
alias kdr "kubectl describe roles"
alias kds "kubectl describe secrets"
alias kdsa "kubectl describe serviceaccounts"
alias kdsvc "kubectl describe services"
alias kdss "kubectl describe statefulsets"
alias kdsc "kubectl describe storageclasses"
alias kdva "kubectl describe volumeattachments"
alias kdwli "kubectl describe workloadimages"

## get
alias kg "kubectl get"
alias kgcm "kubectl get configmaps"
alias kgcrd "kubectl get customresourcedefinitions"
alias kgds "kubectl get daemonsets"
alias kgd "kubectl get deployments"
alias kghpa "kubectl get horizontalpodautoscalers"
alias kgi "kubectl get ingress"
alias kgj "kubectl get jobs"
alias kgns "kubectl get namespaces"
alias kgn "kubectl get nodes"
alias kgpvc "kubectl get persistentvolumeclaims"
alias kgpv "kubectl get persistentvolumes"
alias kgp "kubectl get pods"
alias kgrs "kubectl get replicasets"
alias kgrb "kubectl get rolebindings"
alias kgr "kubectl get roles"
alias kgs "kubectl get secrets"
alias kgsa "kubectl get serviceaccounts"
alias kgsvc "kubectl get services"
alias kgss "kubectl get statefulsets"
alias kgsc "kubectl get storageclasses"
alias kgva "kubectl get volumeattachments"
alias kgwli "kubectl get workloadimages"

## logs
alias kl "kubectl logs"
alias klf "kubectl logs --follow"
alias klfa "kubectl logs --follow --all-containers"
alias klft "kubectl logs --follow --tail 50"
alias klfta "kubectl logs --follow --tail 50 --all-containers"
alias klp "kubectl logs --previous"
alias klpa "kubectl logs --previous --all-containers"
alias klpt "kubectl logs --previous --tail 50"
alias klpta "kubectl logs --previous --tail 50 --all-containers"

## patch
alias kpch "kubectl patch"
alias kpchcm "kubectl patch configmaps"
alias kpchcrd "kubectl patch customresourcedefitions"
alias kpchds "kubectl patch daemonsets"
alias kpchd "kubectl patch deployments"
alias kpchhpa "kubectl patch horizontalpodautoscalers"
alias kpi "kubectl patch ingress"
alias kpchj "kubectl patch jobs"
alias kpchns "kubectl patch namespaces"
alias kpchn "kubectl patch nodes"
alias kpchpvc "kubectl patch persistentvolumeclaims"
alias kpchpv "kubectl patch persistentvolumes"
alias kpchp "kubectl patch pods"
alias kpchrs "kubectl patch replicasets"
alias kpchrb "kubectl patch rolebindings"
alias kpchr "kubectl patch roles"
alias kpchs "kubectl patch secrets"
alias kpchsa "kubectl patch serviceaccounts"
alias kpchsvc "kubectl patch services"
alias kpchss "kubectl patch statefulsets"
alias kpchsc "kubectl patch storageclasses"
alias kpchva "kubectl patch volumeattachments"
alias kpchwli "kubectl patch workloadimages"

## create
alias kcs "kubectl create secret"
alias kcsg "kubectl create secret generic"
## port-forward
alias kpf "kubectl port-forward"
alias kpfa "kubectl port-forward --address"

## run
alias kr "kubectl run"
alias krhelp "echo kr POD_NAME --env=/--expose/--image=/--port=/--restart=/--rm/--stdin/--tty -- [COMMAND] [ARGS]"
alias krdebug="kubectl run debug --image=ubuntu:focal --restart=Never --rm --stdin --tty -- bash"

## extras
alias kdiff="kubectl diff -f"
alias kex "kubectl exec -it"
alias kexw "kubectl exec -it --pod-running-timeout=1m"

## krew addons
alias kvs "kubectl view-secret"
alias kvsa "kubectl view-secret -a"
